version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout
      - run:
          name: "Check Docker"
          command: echo "Hi"
      - run:
          name: "Check Docker"
          command: composer --version
